# Coursera Data Science Specialization
# Practical Machine Learning Course
# Week 4 Project
# John James
# April 22, 2016

##############################################################################
#                             BASE MODELS                                    #
##############################################################################
## ---- formatSummary
library(caret)
library(dplyr)

res.num       <- c(1:28)
res.category  <- c("Bayesian Methods",
                   "Boosting Methods",
                   "Boosting Methods",
                   "Boosting Methods",
                   "Partial Least Squares",
                   "Partial Least Squares",
                   "Partial Least Squares",
                   "Discriminant Analysis",
                   "Discriminant Analysis",
                   "Discriminant Analysis",
                   "Discriminant Analysis",
                   "Discriminant Analysis",
                   "Bagged Methods",
                   "Ensemble",
                   "Ensemble",
                   "Ensemble",
                   "Ensemble",
                   "Instance Based",
                   "Neural Network",
                   "Neural Network",
                   "Regression",
                   "Regression",
                   "Decision Trees",
                   "Decision Trees",
                   "Decision Trees",
                   "Decision Trees",
                   "Decision Trees",
                   "Decision Trees")

res.model  <- c("Naive Bayes",
                "AdaBoost.M1",
                "Stochastic Gradient Boosting",
                "eXtreme Gradient Boosting",
                "Partial Least Squares",
                "Partial Least Squares",
                "Partial Least Squares",
                "Flexible Discriminant Analysis",
                "Mixture Discriminant Analysis",
                "Robust Quadratic Discriminant Analysis",
                "Penalized Discriminant Analysis",
                "Regularized Discriminant Analysis",
                "Bagged CART",
                "Parallel Random Forest",
                "Random Forest",
                "Regularized Random Forest",
                "Weighted Subspace Random Forest",
                "k-Nearest Neighbors",
                "Model Averaged Neural Network",
                "Multi-Layer Perceptron",
                "Multivariate Adaptive Regression Splines",
                "Penalized Multinomial Regression",
                "C5.0",
                "Single C5.0 Tree",
                "Conditional Inference Tree",
                "C4.5-like Trees",
                "Rule-Based Classifier",
                "CART")

res.method  <- c("nb",
                 "AdaBoost.M1",
                 "gbm",
                 "xgbTree",
                 "pls",
                 "simpls",
                 "widekernelpls",
                 "fda",
                 "mda",
                 "QdaCov",
                 "pda",
                 "rda",
                 "treebag",
                 "parRF",
                 "rf",
                 "RRF",
                 "wsrf",
                 "knn",
                 "avNNet",
                 "mlp",
                 "gcvEarth",
                 "multinom",
                 "C5.0",
                 "C5.0Tree",
                 "ctree",
                 "J48",
                 "JRip",
                 "rpart")

res.accuracy  <- c(max(model.nb$results[,4]),
               max(model.AdaBoost.M1$results[,4]),
               max(model.gbm$results[,5]),
               max(model.xgbTree$results[,7]),
               max(model.pls$results[,2]),
               max(model.simpls$results[,2]),
               max(model.widekernelpls$results[,2]),
               max(model.fda$results[,3]),
               max(model.mda$results[,2]),
               max(model.QdaCov$results[,2]),
               max(model.pda$results[,2]),
               max(model.rda$results[,3]),
               max(model.treebag$results[,2]),
               max(model.parRF$results[,2]),
               max(model.rf$results[,2]),
               max(model.RRF$results[,4]),
               max(model.wsrf$results[,2]),
               max(model.knn$results[,2]),
               max(model.avNNet$results[,4]),
               max(model.mlp$results[,2]),
               max(model.gcvEarth$results[,2]),
               max(model.multinom$results[,2]),
               max(model.C5.0$results[,4]),
               max(model.C5.0Tree$results[,2]),
               max(model.ctree$results[,2]),
               max(model.J48$results[,2]),
               max(model.JRip$results[,2]),
               max(model.rpart$results[,2]))

res.kappa <- c(max(model.nb$results[,5]),
               max(model.AdaBoost.M1$results[,5]),
               max(model.gbm$results[,6]),
               max(model.xgbTree$results[,8]),
               max(model.pls$results[,3]),
               max(model.simpls$results[,3]),
               max(model.widekernelpls$results[,3]),
               max(model.fda$results[,4]),
               max(model.mda$results[,3]),
               max(model.QdaCov$results[,3]),
               max(model.pda$results[,3]),
               max(model.rda$results[,4]),
               max(model.treebag$results[,3]),
               max(model.parRF$results[,3]),
               max(model.rf$results[,3]),
               max(model.RRF$results[,5]),
               max(model.wsrf$results[,3]),
               max(model.knn$results[,3]),
               max(model.avNNet$results[,5]),
               max(model.mlp$results[,3]),
               max(model.gcvEarth$results[,3]),
               max(model.multinom$results[,3]),
               max(model.C5.0$results[,5]),
               max(model.C5.0Tree$results[,3]),
               max(model.ctree$results[,3]),
               max(model.J48$results[,3]),
               max(model.JRip$results[,3]),
               max(model.rpart$results[,3]))

res.ensemble1  <- c("***",
                 "***",
                 "***",
                 "***",
                 "***",
                 "***",
                 "***",
                 "***",
                 "***",
                 "***",
                 "***",
                 "",
                 "***",
                 "",
                 "***",
                 "***",
                 "***",
                 "***",
                 "***",
                 "",
                 "***",
                 "***",
                 "***",
                 "***",
                 "***",
                 "",
                 "",
                 "***")

res.ensemble2  <- c("",
                 "***",
                 "***",
                 "***",
                 "",
                 "",
                 "",
                 "",
                 "",
                 "",
                 "",
                 "",
                 "***",
                 "",
                 "***",
                 "***",
                 "***",
                 "***",
                 "",
                 "",
                 "",
                 "",
                 "***",
                 "***",
                 "",
                 "",
                 "",
                 "")

modelSummary  <- data.frame(res.num, res.category, res.model, res.method, res.ensemble1, res.ensemble2, res.accuracy, res.kappa)
names(modelSummary) <- c("Num", "Category", "Model", "Method", "Ensemble 1", "Ensemble 2", "Accuracy", "Kappa")
## ---- end

## ---- compareModels
group1  <- filter(modelSummary, Accuracy > 0.99)
sorted  <- modelSummary[order(modelSummary$Category, -modelSummary$Accuracy),]
group2  <- sorted[!duplicated(sorted$Category),]
group2  <- group2[group2$Accuracy > 0.7,]
## ---- end